"""Focus report — single-class HTML diagnostic page."""
from datetime import datetime
from pathlib import Path
from collections import defaultdict

from .helpers import _esc, _judge_dependency, _is_real_bypass, _LEVEL_NUM
from .layer3_actions import (
    _parse_sin_diagnosis, _severity_css, _sin_suggestion,
    _SIN_BOUNDARY_WEIGHT, _is_data_class,
)


def generate_focus_report(db, class_name, output_path):
    """Generate a standalone HTML report for a single class.

    Pulls responsibility analysis, dependencies (outgoing + incoming),
    and module context from DB. Writes to output_path.
    """
    resp = db.get_responsibility(class_name)
    task = db.get_class_by_name(class_name)
    module_info = db.get_module_info()
    outgoing_deps = db.get_dependencies(class_name) or []
    incoming_deps = db.get_dependents_of_class(class_name) or []
    # All deps needed for data-class detection and bypass analysis
    all_deps = db.get_dependencies() or []

    html = _build_focus_html(class_name, resp, task, module_info,
                             outgoing_deps, incoming_deps, all_deps)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding='utf-8')
    return output_path


def _build_focus_html(class_name, resp, task, module_info,
                      outgoing_deps, incoming_deps, all_deps):
    """Assemble single-class diagnostic HTML."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    profile_html = _section_class_profile(class_name, task, module_info,
                                          outgoing_deps, incoming_deps)
    resp_html = _section_responsibility(class_name, resp)
    sins_html = _section_sins(class_name, resp, all_deps, module_info)
    deps_html = _section_dependencies(class_name, outgoing_deps, incoming_deps,
                                      module_info)

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CodeProbe — {_esc(class_name)} Focus Report</title>
{_css()}
</head>
<body>
<header>
  <h1>CodeProbe — Focus: {_esc(class_name)}</h1>
  <p class="meta">Generated {now} · Single-class deep analysis</p>
</header>
<main>
{profile_html}
{resp_html}
{sins_html}
{deps_html}
</main>
<footer>
  <p>Generated by CodeProbe v3.0 — focus mode</p>
</footer>
</body>
</html>"""


# ─── Section: Class Profile ────────────────────────────────────

def _section_class_profile(class_name, task, module_info,
                           outgoing_deps, incoming_deps):
    """Quick stats card: methods, members, lines, orchestrator flag, dep counts."""
    methods = task['method_count'] if task else 0
    members = task['member_count'] if task else 0
    lines = task['line_count'] if task else 0
    is_orch = bool(task['is_orchestrator']) if task else False
    orchestrator = module_info['orchestrator'] if module_info else ''
    out_count = len(outgoing_deps)
    in_count = len(incoming_deps)

    orch_badge = (' <span class="tag" style="background:#1f6feb;color:#fff">'
                  'Orchestrator</span>') if is_orch else ''

    return f"""\
<section>
  <h2>Class Profile{orch_badge}</h2>
  <div class="stat-grid">
    <div class="stat-box"><div class="num">{methods}</div><div class="label">Methods</div></div>
    <div class="stat-box"><div class="num">{members}</div><div class="label">Members</div></div>
    <div class="stat-box"><div class="num">{lines}</div><div class="label">Lines</div></div>
    <div class="stat-box"><div class="num">{out_count}</div><div class="label">Outgoing Deps</div></div>
    <div class="stat-box"><div class="num">{in_count}</div><div class="label">Incoming Deps</div></div>
  </div>
</section>"""


# ─── Section: Responsibility Analysis ──────────────────────────

def _section_responsibility(class_name, resp):
    """Full responsibility analysis: actual, ideal, SRP violations, extract candidates, tags."""
    if not resp:
        return ('<section><h2>Responsibility Analysis</h2>'
                '<p style="color:var(--muted)">No analysis data yet.</p></section>')

    actual = resp['actual_responsibilities'] or '—'
    ideal = resp['ideal_responsibility'] or '—'
    violations = resp['srp_violations'] or '—'
    candidates = resp['extract_candidates'] or '—'
    tags = resp['responsibility_tags'] or ''

    tags_html = ''
    if tags:
        for tag in tags.split(','):
            tag = tag.strip()
            if tag:
                tags_html += f'<span class="tag">{_esc(tag)}</span> '

    return f"""\
<section>
  <h2>Responsibility Analysis</h2>
  <div class="card">
    <h3>Actual Responsibilities</h3>
    <p>{_esc(actual)}</p>
  </div>
  <div class="card" style="border-left:3px solid var(--success)">
    <h3>Ideal Responsibility (SRP Target)</h3>
    <p>{_esc(ideal)}</p>
  </div>
  <div class="card">
    <h3>SRP Violations</h3>
    <p>{_esc(violations)}</p>
  </div>
  <div class="card">
    <h3>Extract Candidates</h3>
    <p>{_esc(candidates)}</p>
  </div>
  {f'<div class="card"><h3>Tags</h3><p>{tags_html}</p></div>' if tags_html else ''}
</section>"""


# ─── Section: Sin Diagnosis ────────────────────────────────────

def _section_sins(class_name, resp, all_deps, module_info):
    """Sin diagnosis with weight breakdown — reuses Layer 3 logic for one class."""
    orchestrator_class = module_info['orchestrator'] if module_info else ''
    is_orchestrator = {}
    if orchestrator_class:
        is_orchestrator[orchestrator_class] = True

    # Build full dep graph for context
    flat_deps = {}
    all_local = set()
    for d in all_deps:
        src = d['source_class']
        all_local.add(src)
        if not d['target_is_external']:
            all_local.add(d['target_class'])
        flat_deps.setdefault(src, []).append({
            'target': d['target_class'],
            'level': d['level_name'],
            'source': d['source_evidence'],
            'target_is_external': bool(d['target_is_external']),
        })

    incoming_count = {}
    incoming_sources = defaultdict(set)
    outgoing_count = {}
    for cn, dep_list in flat_deps.items():
        targets = set()
        for dep in dep_list:
            tgt = dep['target']
            if not dep.get('target_is_external', False):
                targets.add(tgt)
                incoming_sources[tgt].add(cn)
        outgoing_count[cn] = len(targets)
    for tgt, srcs in incoming_sources.items():
        incoming_count[tgt] = len(srcs)

    resp_map = {class_name: resp} if resp else {}
    items = []

    # Class-level sins
    if resp:
        sin_diag = resp['sin_diagnosis'] or ''
        if sin_diag:
            parsed_sins = _parse_sin_diagnosis(sin_diag)
            if _is_data_class(class_name, flat_deps, incoming_count,
                              outgoing_count, resp_map):
                parsed_sins = [
                    (sn, sev, ev) for sn, sev, ev in parsed_sins
                    if sn.replace(' ', '').lower() in ('hiddenstate', 'knowledgeleakage')
                ]
            for sin_name, severity, evidence in parsed_sins:
                w_boundary = _SIN_BOUNDARY_WEIGHT.get(sin_name, 20)
                w_impact = _calc_impact(class_name, incoming_count, outgoing_count)
                w_role = _calc_role(class_name, is_orchestrator, incoming_count)
                weight = w_boundary + w_impact + w_role
                sev_css = _severity_css(severity)
                suggestion = _sin_suggestion(sin_name)
                breakdown = (f'{sin_name} = {w_boundary} boundary'
                             f' + {w_impact} impact + {w_role} role')
                items.append((sin_name, sev_css, evidence, suggestion,
                              weight, breakdown))

    # Bypass detection for this class
    dep_list = flat_deps.get(class_name, [])
    for dep in dep_list:
        target = dep['target']
        level = dep['level']
        health, reason = _judge_dependency(
            class_name, dep, orchestrator_class, all_local)
        if health == 'warn' and 'bypass' in reason.lower():
            if _is_real_bypass(class_name, target, orchestrator_class,
                               level, incoming_count):
                w_boundary = 40 + (10 if _LEVEL_NUM.get(level, 0) >= 3 else 0)
                w_impact = _calc_impact(class_name, incoming_count, outgoing_count)
                w_role = _calc_role(class_name, is_orchestrator, incoming_count)
                weight = w_boundary + w_impact + w_role
                evidence = f'Direct {level} to {target}, bypassing orchestrator'
                breakdown = (f'bypass = {w_boundary} boundary'
                             f' + {w_impact} impact + {w_role} role')
                items.append(('Orchestrator Bypass', 'p-warn', evidence,
                              'Route through orchestrator or extract interface',
                              weight, breakdown))

    if not items:
        return ('<section><h2>Sin Diagnosis</h2>'
                '<div class="card"><p class="health-good">'
                'No design sins detected. Class looks healthy.</p></div></section>')

    items.sort(key=lambda x: -x[4])

    items_html = ''
    for sin_name, sev_css, evidence, suggestion, weight, breakdown in items:
        items_html += f"""\
  <div class="action-item">
    <span class="priority {sev_css}">{_esc(sin_name)}</span>
    <span style="color:var(--muted);font-size:0.8rem" title="{_esc(breakdown)}">&#x26A1;{weight}</span>
    <span style="color:var(--muted);font-size:0.85rem"> &mdash; {_esc(evidence)}</span>
    <div class="action-desc" style="color:var(--primary)">&#x2192; {_esc(suggestion)}</div>
  </div>\n"""

    return f"""\
<section>
  <h2>Sin Diagnosis</h2>
  <p style="color:var(--muted)">Design issues detected, sorted by &#x26A1; refactoring priority.</p>
  {items_html}
</section>"""


# ─── Section: Dependencies ─────────────────────────────────────

def _section_dependencies(class_name, outgoing_deps, incoming_deps, module_info):
    """Outgoing + incoming dependency tables with health judgment."""
    orchestrator_class = module_info['orchestrator'] if module_info else ''
    all_local = set()
    for d in list(outgoing_deps) + list(incoming_deps):
        all_local.add(d['source_class'])
        if not d['target_is_external']:
            all_local.add(d['target_class'])

    # Outgoing
    out_html = ''
    if outgoing_deps:
        out_rows = ''
        for d in outgoing_deps:
            dep_dict = {
                'target': d['target_class'],
                'level': d['level_name'],
                'source': d['source_evidence'],
                'target_is_external': bool(d['target_is_external']),
            }
            health, reason = _judge_dependency(
                class_name, dep_dict, orchestrator_class, all_local)
            hcss = f'health-{health}'
            lv_css = d['level_name'].lower().replace('-', '')
            ext = ' <span class="tag">ext</span>' if d['target_is_external'] else ''
            out_rows += (f'<tr><td>{_esc(d["target_class"])}{ext}</td>'
                         f'<td><span class="dep-level {lv_css}">{_esc(d["level_name"])}</span></td>'
                         f'<td class="{hcss}">{_esc(reason)}</td></tr>\n')
        out_html = f"""\
  <div class="card">
    <h3>Outgoing Dependencies ({len(outgoing_deps)})</h3>
    <table>
      <tr><th>Target</th><th>Level</th><th>Health</th></tr>
      {out_rows}
    </table>
  </div>"""

    # Incoming
    in_html = ''
    if incoming_deps:
        in_rows = ''
        for d in incoming_deps:
            dep_dict = {
                'target': d['target_class'],
                'level': d['level_name'],
                'source': d['source_evidence'],
                'target_is_external': bool(d['target_is_external']),
            }
            health, reason = _judge_dependency(
                d['source_class'], dep_dict, orchestrator_class, all_local)
            hcss = f'health-{health}'
            lv_css = d['level_name'].lower().replace('-', '')
            in_rows += (f'<tr><td>{_esc(d["source_class"])}</td>'
                        f'<td><span class="dep-level {lv_css}">{_esc(d["level_name"])}</span></td>'
                        f'<td class="{hcss}">{_esc(reason)}</td></tr>\n')
        in_html = f"""\
  <div class="card">
    <h3>Incoming Dependencies ({len(incoming_deps)})</h3>
    <table>
      <tr><th>Source</th><th>Level</th><th>Health</th></tr>
      {in_rows}
    </table>
  </div>"""

    if not out_html and not in_html:
        return ('<section><h2>Dependencies</h2>'
                '<p style="color:var(--muted)">No dependencies recorded.</p></section>')

    return f"""\
<section>
  <h2>Dependencies</h2>
  {out_html}
  {in_html}
</section>"""


# ─── Helpers (local to avoid circular imports) ─────────────────

def _calc_impact(cn, incoming_count, outgoing_count):
    return incoming_count.get(cn, 0) * 8 + outgoing_count.get(cn, 0) * 5


def _calc_role(cn, is_orchestrator, incoming_count):
    bonus = 0
    if is_orchestrator.get(cn):
        bonus += 15
    if incoming_count.get(cn, 0) >= 3:
        bonus += 10
    return bonus


def _css():
    """Same dark theme as main report, compact version."""
    return """\
<style>
  :root {
    --bg: #0d1117; --card-bg: #161b22; --border: #30363d;
    --primary: #58a6ff; --danger: #f85149; --success: #3fb950;
    --warning: #d29922; --text: #c9d1d9; --muted: #8b949e;
    --accent: #1f6feb; --surface: #21262d;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace;
         background: var(--bg); color: var(--text); line-height: 1.6; }
  header { background: linear-gradient(135deg, #1f6feb 0%, #238636 100%);
           color: #fff; padding: 2.5rem; text-align: center; }
  header h1 { font-size: 1.8rem; margin-bottom: 0.3rem; font-weight: 600; }
  header .meta { opacity: 0.8; font-size: 0.9rem; }
  main { max-width: 900px; margin: 2rem auto; padding: 0 1.5rem; }
  footer { text-align: center; padding: 2rem; color: var(--muted); font-size: 0.85rem;
           border-top: 1px solid var(--border); }
  section { margin-bottom: 2.5rem; }
  h2 { font-size: 1.3rem; margin-bottom: 1rem; padding-bottom: 0.5rem;
       border-bottom: 1px solid var(--border); color: var(--primary); }
  .card { background: var(--card-bg); border: 1px solid var(--border);
          border-radius: 6px; padding: 1.2rem; margin-bottom: 1rem; }
  .card h3 { font-size: 1rem; margin-bottom: 0.5rem; color: #f0f6fc; }
  .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 1rem; }
  .stat-box { background: var(--card-bg); border: 1px solid var(--border);
              border-radius: 6px; padding: 1rem; text-align: center; }
  .stat-box .num { font-size: 2rem; font-weight: 700; color: var(--primary); }
  .stat-box .label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase;
                     letter-spacing: 0.05em; }
  .tag { display: inline-block; background: var(--surface); padding: 0.15rem 0.5rem;
         border-radius: 20px; font-size: 0.75rem; margin: 0.1rem; color: var(--text);
         border: 1px solid var(--border); }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
  th, td { padding: 0.6rem 0.8rem; text-align: left; border-bottom: 1px solid var(--border); }
  th { background: var(--surface); font-weight: 600; font-size: 0.85rem; color: var(--muted);
       text-transform: uppercase; letter-spacing: 0.05em; }
  td { font-size: 0.9rem; }
  .dep-level { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 3px;
               font-size: 0.75rem; font-weight: 600; }
  .lv0 { background: #1a3a2a; color: #3fb950; }
  .lv1 { background: #1a2d4a; color: #58a6ff; }
  .lv2 { background: #0d3321; color: #3fb950; }
  .lv3 { background: #2d1b00; color: #d29922; }
  .lv4 { background: #3d2800; color: #d29922; }
  .lv5 { background: #3d1215; color: #f85149; }
  .health-good { color: #3fb950; }
  .health-warn { color: #d29922; }
  .health-bad { color: #f85149; }
  .action-item { background: var(--card-bg); border: 1px solid var(--border);
                 border-radius: 6px; padding: 1rem 1.2rem; margin-bottom: 0.7rem; }
  .action-item .priority { display: inline-block; padding: 0.15rem 0.6rem;
                           border-radius: 3px; font-weight: 700; font-size: 0.8rem;
                           margin-right: 0.5rem; }
  .p-crit { background: #3d1215; color: #f85149; border: 1px solid #da3633; }
  .p-warn { background: #2d1b00; color: #d29922; border: 1px solid #9e6a03; }
  .p-info { background: #1a3a2a; color: #3fb950; border: 1px solid #238636; }
  .action-desc { color: var(--muted); margin-top: 0.3rem; font-size: 0.85rem; }
  .score-bad { background: #3d1215; color: #f85149; border: 1px solid #da3633; }
  .score-warn { background: #2d1b00; color: #d29922; border: 1px solid #9e6a03; }
  .score-good { background: #0d3321; color: #3fb950; border: 1px solid #238636; }
  p { margin-bottom: 0.5rem; }
</style>"""
