"""Report generator — assembles all sections into final HTML."""
from pathlib import Path
from datetime import datetime

from .layer1_workflow import _section_responsibility_map
from .layer2_deps import _section_dependency_health
from .layer3_actions import _section_action_items
from .sections import _section_overview


def generate_html_report(db, output_path, reader=None):
    """Read all data from DB, generate three-layer diagnostic HTML report.
    reader is accepted for backward compatibility but NOT used."""
    stats = db.get_stats()
    tasks = db.get_all_tasks()
    resps = db.get_all_responsibilities()
    module_info = db.get_module_info()
    all_deps = db.get_dependencies()

    html = _build_html(stats, tasks, resps or [], module_info, all_deps or [])
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding='utf-8')
    return output_path


def _build_html(stats, tasks, resps, module_info, all_deps):
    """Assemble three-layer diagnostic HTML page."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    overview_html = _section_overview(stats)
    resp_map_html = _section_responsibility_map(resps, tasks, module_info, all_deps)
    dep_health_html = _section_dependency_health(all_deps, resps, module_info)
    action_html = _section_action_items(resps, all_deps, module_info)

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CodeProbe \u2014 Design Diagnosis Report</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>mermaid.initialize({{startOnLoad:true, theme:'default', flowchart:{{curve:'basis'}}, securityLevel:'loose'}});</script>
{_css()}
</head>
<body>
<header>
  <h1>CodeProbe \u2014 Design Diagnosis</h1>
  <p class="meta">Generated {now} \u00b7 Framework: OOD Complete Guide (Three-layer diagnosis + 6-level dependency pyramid)</p>
</header>
<main>
{overview_html}
{resp_map_html}
{dep_health_html}
{action_html}
</main>
<footer>
  <p>Generated by CodeProbe v3.0</p>
</footer>
</body>
</html>"""


def _css():
    return """\
<style>
  :root {
    --bg: #0d1117; --card-bg: #161b22; --border: #30363d;
    --primary: #58a6ff; --danger: #f85149; --success: #3fb950;
    --warning: #d29922; --text: #c9d1d9; --muted: #8b949e;
    --accent: #1f6feb; --surface: #21262d;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace;
         background: var(--bg); color: var(--text); line-height: 1.6; }
  header { background: linear-gradient(135deg, #1f6feb 0%, #238636 100%);
           color: #fff; padding: 2.5rem; text-align: center; }
  header h1 { font-size: 1.8rem; margin-bottom: 0.3rem; font-weight: 600; }
  header .meta { opacity: 0.8; font-size: 0.9rem; }
  main { max-width: 1100px; margin: 2rem auto; padding: 0 1.5rem; }
  footer { text-align: center; padding: 2rem; color: var(--muted); font-size: 0.85rem;
           border-top: 1px solid var(--border); }
  section { margin-bottom: 2.5rem; }
  h2 { font-size: 1.3rem; margin-bottom: 1rem; padding-bottom: 0.5rem;
       border-bottom: 1px solid var(--border); color: var(--primary); }
  .card { background: var(--card-bg); border: 1px solid var(--border);
          border-radius: 6px; padding: 1.2rem; margin-bottom: 1rem; }
  .card h3 { font-size: 1rem; margin-bottom: 0.5rem; color: #f0f6fc; }
  .scores { display: flex; gap: 0.8rem; margin: 0.5rem 0; flex-wrap: wrap; }
  .score-badge { display: inline-block; padding: 0.2rem 0.7rem;
                 border-radius: 20px; font-weight: 600; font-size: 0.8rem; }
  .score-good { background: #0d3321; color: #3fb950; border: 1px solid #238636; }
  .score-warn { background: #2d1b00; color: #d29922; border: 1px solid #9e6a03; }
  .score-bad { background: #3d1215; color: #f85149; border: 1px solid #da3633; }
  .score-na { background: var(--surface); color: var(--muted); border: 1px solid var(--border); }
  .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; }
  .stat-box { background: var(--card-bg); border: 1px solid var(--border);
              border-radius: 6px; padding: 1rem; text-align: center; }
  .stat-box .num { font-size: 2rem; font-weight: 700; color: var(--primary); }
  .stat-box .label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase;
                     letter-spacing: 0.05em; }
  .tag { display: inline-block; background: var(--surface); padding: 0.15rem 0.5rem;
         border-radius: 20px; font-size: 0.75rem; margin: 0.1rem; color: var(--text);
         border: 1px solid var(--border); }
  .mermaid { text-align: center; margin: 1rem 0; background: #fff; border-radius: 6px;
             padding: 1rem; }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
  th, td { padding: 0.6rem 0.8rem; text-align: left; border-bottom: 1px solid var(--border); }
  th { background: var(--surface); font-weight: 600; font-size: 0.85rem; color: var(--muted);
       text-transform: uppercase; letter-spacing: 0.05em; }
  td { font-size: 0.9rem; }
  .phase-card { border-left: 3px solid var(--primary); }
  .issue-text { color: var(--danger); }
  pre { background: var(--surface); padding: 0.8rem; border-radius: 6px;
        overflow-x: auto; font-size: 0.85rem; border: 1px solid var(--border); }
  .dep-level { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 3px;
               font-size: 0.75rem; font-weight: 600; }
  .lv0 { background: #1a3a2a; color: #3fb950; }
  .lv1 { background: #1a2d4a; color: #58a6ff; }
  .lv2 { background: #0d3321; color: #3fb950; }
  .lv4 { background: #3d2800; color: #d29922; }
  .lv5 { background: #3d1215; color: #f85149; }
  .legend { display: flex; gap: 1.5rem; flex-wrap: wrap; margin: 0.5rem 0; font-size: 0.85rem; }
  .legend-item { display: flex; align-items: center; gap: 0.3rem; }
  .legend-dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
  .summary-bar { display: flex; gap: 2rem; flex-wrap: wrap; padding: 0.8rem 0;
                 font-size: 0.9rem; color: var(--muted); }
  .summary-bar span { white-space: nowrap; }
  .health-good { color: #3fb950; }
  .health-warn { color: #d29922; }
  .health-bad { color: #f85149; }
  .action-item { background: var(--card-bg); border: 1px solid var(--border);
                 border-radius: 6px; padding: 1rem 1.2rem; margin-bottom: 0.7rem; }
  .action-item .priority { display: inline-block; padding: 0.15rem 0.6rem;
                           border-radius: 3px; font-weight: 700; font-size: 0.8rem;
                           margin-right: 0.5rem; }
  .p-crit { background: #3d1215; color: #f85149; border: 1px solid #da3633; }
  .p-warn { background: #2d1b00; color: #d29922; border: 1px solid #9e6a03; }
  .p-info { background: #1a3a2a; color: #3fb950; border: 1px solid #238636; }
  .action-item .class-name { font-weight: 600; color: #f0f6fc; }
  .action-item .action-desc { color: var(--muted); margin-top: 0.3rem; font-size: 0.85rem; }
  .lv3 { background: #2d1b00; color: #d29922; }
  .dep-table td:first-child { font-weight: 600; }
  .external > rect { fill: #2d333b !important; stroke: #444c56 !important; stroke-dasharray: 5 5; }
  .external > text { fill: #8b949e !important; }
</style>"""
